In [7]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
crimes_df = pd.read_csv('TransformGainesville_CrimesALL.csv')
crimes_df

,Unnamed: 0,ID,CFS,CFS_Type,Classification,offenseDate,offenseHour,offenseDOW,reportDate,reportHour,...,longitude,location,date,month,day,year,fullDate,DOW,time,moonPhase
0,0,221009267,Domestic Aggravated Battery,Battery,Person,2021-07-04 21:24:00,21,Sunday,7/4/2021 22:37,22,...,-82.326069,POINT (-82.326069 29.688534000000004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,221009608,Domestic Aggravated Battery,Battery,Person,2021-07-11 22:54:00,22,Sunday,7/11/2021 22:55,22,...,-82.387148,POINT (-82.387148 29.632687000000004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,221009391,Domestic Aggravated Battery,Battery,Person,2021-07-07 19:12:00,19,Wednesday,7/7/2021 19:13,19,...,-82.299390,POINT (-82.29939 29.640249),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,221009308,Domestic Aggravated Battery,Battery,Person,2021-07-06 07:26:00,7,Tuesday,7/6/2021 7:27,7,...,-82.398242,POINT (-82.398242 29.641625),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,221011388,Domestic Aggravated Battery,Battery,Person,2021-08-16 17:25:00,17,Monday,8/16/2021 17:26,17,...,-82.326069,POINT (-82.326069 29.688534000000004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44868,44868,219004357,Battery (security Guard/officer Aggravated),Battery,Person,2019-03-14 22:45:00,22,Thursday,3/15/2019 0:50,0,...,-82.411597,POINT (-82.411597 29.659699),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44869,44869,218014815,Criminal Mischief,Other,Property,2018-08-15 12:15:00,12,Wednesday,8/15/2018 13:33,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44870,44870,218019557,Theft Grand - Purse Snatching,Theft,Property,2018-10-23 14:53:00,14,Tuesday,10/23/2018 14:53,14,...,-82.339167,POINT (-82.339167 29.677320999999996),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44871,44871,218017216,Falsely Personating Officer,Gov Reg Vio,Government,2018-09-18 21:46:00,21,Tuesday,9/18/2018 22:55,22,...,-82.377955,POINT (-82.377955 29.617822000000004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44872,44872,218011979,Gas Drive Off,Theft,Property,2018-07-01 19:18:00,19,Sunday,7/1/2018 20:03,20,...,-82.356193,POINT (-82.356193 29.712461),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Classify offense type into NON-VIOLENT/Violent

In [ ]:
# Drop NaN ?

In [ ]:
# Identify most common attributes

In [6]:
crimes_df = crimes_df.dtypes[crimes_df.dtypes == "object"].index.tolist()

AttributeError: 'list' object has no attribute 'dtypes'